# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/yair/clion-2017.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/yair/clion-2017.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/yair/CLionProjects/mission 2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/yair/CLionProjects/mission 2/cmake-build-debug"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/yair/clion-2017.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/yair/clion-2017.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/yair/CLionProjects/mission 2/cmake-build-debug/CMakeFiles" "/home/yair/CLionProjects/mission 2/cmake-build-debug/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/yair/CLionProjects/mission 2/cmake-build-debug/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named untitled

# Build rule for target.
untitled: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 untitled
.PHONY : untitled

# fast build rule for target.
untitled/fast:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/build
.PHONY : untitled/fast

AIPlayer.o: AIPlayer.cpp.o

.PHONY : AIPlayer.o

# target to build an object file
AIPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/AIPlayer.cpp.o
.PHONY : AIPlayer.cpp.o

AIPlayer.i: AIPlayer.cpp.i

.PHONY : AIPlayer.i

# target to preprocess a source file
AIPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/AIPlayer.cpp.i
.PHONY : AIPlayer.cpp.i

AIPlayer.s: AIPlayer.cpp.s

.PHONY : AIPlayer.s

# target to generate assembly for a file
AIPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/AIPlayer.cpp.s
.PHONY : AIPlayer.cpp.s

Board.o: Board.cpp.o

.PHONY : Board.o

# target to build an object file
Board.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Board.cpp.o
.PHONY : Board.cpp.o

Board.i: Board.cpp.i

.PHONY : Board.i

# target to preprocess a source file
Board.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Board.cpp.i
.PHONY : Board.cpp.i

Board.s: Board.cpp.s

.PHONY : Board.s

# target to generate assembly for a file
Board.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Board.cpp.s
.PHONY : Board.cpp.s

ConsolePlayer.o: ConsolePlayer.cpp.o

.PHONY : ConsolePlayer.o

# target to build an object file
ConsolePlayer.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/ConsolePlayer.cpp.o
.PHONY : ConsolePlayer.cpp.o

ConsolePlayer.i: ConsolePlayer.cpp.i

.PHONY : ConsolePlayer.i

# target to preprocess a source file
ConsolePlayer.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/ConsolePlayer.cpp.i
.PHONY : ConsolePlayer.cpp.i

ConsolePlayer.s: ConsolePlayer.cpp.s

.PHONY : ConsolePlayer.s

# target to generate assembly for a file
ConsolePlayer.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/ConsolePlayer.cpp.s
.PHONY : ConsolePlayer.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Game.cpp.s
.PHONY : Game.cpp.s

GameLogic.o: GameLogic.cpp.o

.PHONY : GameLogic.o

# target to build an object file
GameLogic.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/GameLogic.cpp.o
.PHONY : GameLogic.cpp.o

GameLogic.i: GameLogic.cpp.i

.PHONY : GameLogic.i

# target to preprocess a source file
GameLogic.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/GameLogic.cpp.i
.PHONY : GameLogic.cpp.i

GameLogic.s: GameLogic.cpp.s

.PHONY : GameLogic.s

# target to generate assembly for a file
GameLogic.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/GameLogic.cpp.s
.PHONY : GameLogic.cpp.s

GameLogic1.o: GameLogic1.cpp.o

.PHONY : GameLogic1.o

# target to build an object file
GameLogic1.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/GameLogic1.cpp.o
.PHONY : GameLogic1.cpp.o

GameLogic1.i: GameLogic1.cpp.i

.PHONY : GameLogic1.i

# target to preprocess a source file
GameLogic1.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/GameLogic1.cpp.i
.PHONY : GameLogic1.cpp.i

GameLogic1.s: GameLogic1.cpp.s

.PHONY : GameLogic1.s

# target to generate assembly for a file
GameLogic1.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/GameLogic1.cpp.s
.PHONY : GameLogic1.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Player.cpp.s
.PHONY : Player.cpp.s

Point.o: Point.cpp.o

.PHONY : Point.o

# target to build an object file
Point.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Point.cpp.o
.PHONY : Point.cpp.o

Point.i: Point.cpp.i

.PHONY : Point.i

# target to preprocess a source file
Point.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Point.cpp.i
.PHONY : Point.cpp.i

Point.s: Point.cpp.s

.PHONY : Point.s

# target to generate assembly for a file
Point.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/Point.cpp.s
.PHONY : Point.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/untitled.dir/build.make CMakeFiles/untitled.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... untitled"
	@echo "... AIPlayer.o"
	@echo "... AIPlayer.i"
	@echo "... AIPlayer.s"
	@echo "... Board.o"
	@echo "... Board.i"
	@echo "... Board.s"
	@echo "... ConsolePlayer.o"
	@echo "... ConsolePlayer.i"
	@echo "... ConsolePlayer.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... GameLogic.o"
	@echo "... GameLogic.i"
	@echo "... GameLogic.s"
	@echo "... GameLogic1.o"
	@echo "... GameLogic1.i"
	@echo "... GameLogic1.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Point.o"
	@echo "... Point.i"
	@echo "... Point.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

